### ISSUE TITLE
Design Docs Feedback: MVP list and Schema

### ISSUE THREAD

**Issue by RosemaryGonzaga** [debevoise/Tilda#1]
Hey Simon, great work on your MVP list and Schema - I appreciate the thought you put into them. I have some comments on those below, and I'll send feedback on the Sample State Shape and Frontend / Backend routes shortly. We'll discuss all this in person on Monday, but feel free to comment leave comments if you need clarification or disagree with anything.

DESIGN DOCS FEEDBACK - MVP list:

1. General
   - [x] Add a timeline (projected dates for each feature)
2. Feature #2: New signup and login
   - [x] Include a demo account so users can try out the site without signing up
3. Feature #3: Song/Playlist Crud
   - [x] I recommend removing the 3rd bullet point. Songs, Albums, and Artists should already be seeded on the app; regular users can read these resources, but they cannot create, update, or destroy them.
     - Full CRUD functionality should apply to Playlists only.
     - If you want to implement artists as special types of users with the ability to CRUD songs, I’d recommend saving Artists for a bonus feature. For the main MVP, it would be easier to focus on replicating the functionality available to a regular user.
4. Feature #6: Following playlists / Friending users
   - [x] I’m unfamiliar with the social aspect of Spotify. From what I can tell, users can follow Artists but not other users (who are non-artists). Users can also like playlists in the way that they can like songs and albums. We can discuss during our 1:1 on Monday.

DESIGN DOCS FEEDBACK - Database Schema:

1. General
   - [x] Add timestamps to all tables (`created_at` and `updated_at` columns)
   - [x] Don’t forget to make your column names snake_case! :)
2. Users
   - [x] Add columns for `name`, `birth_date`, `gender`. All three should have `not null` constraints (on Spotify, all three are required to sign up.)
3. Artists
   - [x] Add an artists table, which albums can reference via the foreign_key `:artist_id`. As mentioned above, I recommend treating Artists as a separate entity from Users.
4. Songs
   - [x] Remove the `song_file` column; since you’ll be storing song files in a cloud service (AWS S3) and managing references to those files via Active Storage, you won’t need the `song_file` column.
5. Albums
   - [x] Remove the `album_artwork_link` column (similar to the song files, the album artwork is another resource that you’ll store with AWS, and you don’t need a key to reference that resource).
6. Playlist Songs
   - [ ] Add a unique constraint on the combination of playlist_id and song_id, to ensure a user can’t add the same song to the same playlist twice.
7. Likes
   - [x] Agree that likes should be polymorphic. For that, you’ll need a `likeable_type` and `likeable_id` columns. More info this reading: https://guides.rubyonrails.org/association_basics.html#polymorphic-associations

**Comment by debevoise** [comment]
Thanks for the feedback Rosemary! Can't wait to chat with you on Monday. I've updated design docs to reflect your suggested changes except for one point: I omitted the unique constraint on Playlist-Songs because Spotify allows users to add repeated songs to playlists.
